"""add contract attachments

Revision ID: 3113787cb848
Revises: a5082b0c59c2
Create Date: 2026-09-01 09:31:20.099061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3113787cb848'
down_revision: Union[str, None] = 'a5082b0c59c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contract_approvals_approver_id', table_name='contract_approvals')
    op.drop_index('ix_contract_approvals_contract_id', table_name='contract_approvals')
    op.drop_index('ix_contract_approvals_status', table_name='contract_approvals')
    op.drop_table('contract_approvals')
    op.alter_column('contract_attachments', 'object_key',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('contract_attachments', 'content_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_index(op.f('ix_contract_attachments_uploaded_by'), 'contract_attachments', ['uploaded_by'], unique=False)
    op.create_unique_constraint(None, 'contract_attachments', ['object_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contract_attachments', type_='unique')
    op.drop_index(op.f('ix_contract_attachments_uploaded_by'), table_name='contract_attachments')
    op.alter_column('contract_attachments', 'content_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('contract_attachments', 'object_key',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_table('contract_approvals',
    sa.Column('approval_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('contract_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('step_no', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('approver_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.contract_id'], name='contract_approvals_contract_id_fkey'),
    sa.PrimaryKeyConstraint('approval_id', name='contract_approvals_pkey')
    )
    op.create_index('ix_contract_approvals_status', 'contract_approvals', ['status'], unique=False)
    op.create_index('ix_contract_approvals_contract_id', 'contract_approvals', ['contract_id'], unique=False)
    op.create_index('ix_contract_approvals_approver_id', 'contract_approvals', ['approver_id'], unique=False)
    # ### end Alembic commands ###
