"""enhance outbox event tracking

Revision ID: a5082b0c59c2
Revises: b27efc55ea82
Create Date: 2026-08-29 13:38:59.602625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5082b0c59c2'
down_revision: Union[str, None] = 'b27efc55ea82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_events', sa.Column('last_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbox_events', 'last_error')
    # ### end Alembic commands ###
