"""add contract approval table

Revision ID: b27efc55ea82
Revises: 47dc22608368
Create Date: 2026-08-29 00:05:46.445927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b27efc55ea82'
down_revision: Union[str, None] = '47dc22608368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_approvals',
    sa.Column('approval_id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('step_no', sa.Integer(), nullable=False),
    sa.Column('approver_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.contract_id'], ),
    sa.PrimaryKeyConstraint('approval_id')
    )
    op.create_index(op.f('ix_contract_approvals_approver_id'), 'contract_approvals', ['approver_id'], unique=False)
    op.create_index(op.f('ix_contract_approvals_contract_id'), 'contract_approvals', ['contract_id'], unique=False)
    op.create_index(op.f('ix_contract_approvals_status'), 'contract_approvals', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_approvals_status'), table_name='contract_approvals')
    op.drop_index(op.f('ix_contract_approvals_contract_id'), table_name='contract_approvals')
    op.drop_index(op.f('ix_contract_approvals_approver_id'), table_name='contract_approvals')
    op.drop_table('contract_approvals')
    # ### end Alembic commands ###
