"""add contract_number to contracts table

Revision ID: d499a72c42a0
Revises: e77b6bac02e1
Create Date: 2026-08-28 10:14:33.532982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd499a72c42a0'
down_revision: Union[str, None] = 'e77b6bac02e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('contract_number', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_contracts_contract_number'), 'contracts', ['contract_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contracts_contract_number'), table_name='contracts')
    op.drop_column('contracts', 'contract_number')
    # ### end Alembic commands ###
