apiVersion: v1
kind: Service
metadata:
  name: contract-service
  namespace: business-management
  labels:
    app: contract-service
spec:
  type: ClusterIP
  ports:
  - port: 8002
    targetPort: 8002
    protocol: TCP
    name: http
  selector:
    app: contract-service
